homeassistant:
  # Name of the location where Home Assistant is running
  name: Home
  # Location required to calculate the time the sun rises and sets
  latitude: 55.78027655
  longitude: 37.47523303
  # Impacts weather/sunrise data (altitude above sea level in meters)
  elevation: 151
  # metric for Metric, imperial for Imperial
  unit_system: metric
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: Europe/Moscow
  # Customization file
  customize: !include customize.yaml

# Show links to resources in log and frontend
introduction:

# Enables the frontend
frontend:

# Enables configuration UI
config:

# Uncomment this if you are using SSL/TLS, running in Docker container, etc.
# http:
#   base_url: example.duckdns.org:8123

# Checks for available updates
# Note: This component will send some information about your system to
# the developers to assist with development of Home Assistant.
# For more information, please see:
# https://home-assistant.io/blog/2016/10/25/explaining-the-updater/
updater:
  # Optional, allows Home Assistant developers to focus on popular components.
  # include_used_components: true

# Discover some devices automatically
discovery:

# Allows you to issue voice commands from the frontend in enabled browsers
conversation:

# Enables support for tracking state changes over time
history:

# View all events in a logbook
logbook:

# Enables a map showing the location of tracked devices
map:

# Track the sun
sun:

# Weather prediction
sensor:
  - platform: yr
    name: 'Weather'
    forecast: 24
    monitored_conditions:
      - temperature
      - symbol
#      - precipitation
      - windSpeed
#      - pressure
#      - windDirection
#      - humidity
#      - fog
#      - cloudiness
#      - lowClouds
#      - mediumClouds
#      - highClouds
#      - dewpointTemperature

# Text to speech
tts:
  - platform: google

# Cloud
cloud:

group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml

#Web panel - Configurator, router, etc...
panel_iframe:
  configurator:
    title: 'Configurator'
    icon: mdi:wrench
    url: http://hassio.local:3218
  ide:
    title: 'IDE'
    icon: mdi:code-braces
    url: http://192.168.1.200:8321/ide.html
  mdiindex:
    title: 'MDI Icon Index'
    icon: mdi:vector-square
    url: https://cdn.rawgit.com/james-fry/home-assistant-mdi/efd95d7a/home-assistant-mdi.html
    
#Philips Zhirui bulb ob WiFi
light:
  - platform: xiaomi_miio
    name: Xiaomi Philips Smart LED Ball
    host: 192.168.1.210
    token: 6f560a3d4743e8aae6ddb07cd000bc8e
    model: philips.light.bulb
    
#Enable Bluetooth    
device_tracker:
  - platform: bluetooth_tracker    
  - platform: bluetooth_le_tracker      
# Redmomd cetle G200S BLE    
#switch:
#  - platform: R4S_G200S
#    mac: 'FF:FF:FF:FF:FF:FF' # insert your mac
#    key: 'ffffffffffffffff' # generate your own 8 byte key
#    scan_interval: 90
#    device: hci0 # your bluetooth device